name: MediumApiCheck

on: 
  push:
    branches:    
      - master 
  schedule:
  - cron: 0 2 * * 0-6

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run random command which throw error
   # - if: github.event_name == 'repository_dispatch'
      run: cargo test
        
